name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Altere para a branch principal do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python e dependências
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Fazer deploy para GitHub Pages
        run: mkdocs gh-deploy --force

