site_name: Documentacao TI

nav:
  - Início: index.md
  - 'Gennera':
    - Login: login/login.md
    - Tela Inicial: telaInicio/telaInicio.md
    - 'Módulos' :
      - Acadêmico: academico/academico.md

theme:
  name: material
  palette:
    - scheme: light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Alternar para modo escuro
      primary: red
      accent: indigo

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Alternar para modo claro
      primary: red
      accent: light red

  font:
    text: Poppins

  nav_style: dark
  language: pt

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigations.indexes
    - content.code.copy
    #- toc.integrate
    - search.suggest
    - search.highlight

