name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Ou a branch principal do seu repositório

permissions:
  contents: write  # Permite a ação fazer push no branch gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar MkDocs e plugins
        run: pip install mkdocs mkdocs-material

      - name: Fazer deploy para GitHub Pages
        run: mkdocs gh-deploy --force
 
